# Generated by Django 3.2.9 on 2021-12-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_discut'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
                ('to_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_cart', to='account.cart')),
            ],
        ),
    ]
