# Generated by Django 3.2.9 on 2021-12-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='sliderimgs/', verbose_name='Tovar rasm')),
                ('name', models.CharField(max_length=300, verbose_name='Tovar nomi')),
                ('name_plus', models.CharField(blank=True, max_length=200, verbose_name="Tovar nomi qo'shimcha")),
                ('about', models.TextField(verbose_name='Tovar haqida')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
