# Generated by Django 3.2.9 on 2021-12-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='prductsimgs/', verbose_name='Tovar rasm')),
                ('name', models.CharField(max_length=200, verbose_name='Tovar nomi')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='*')),
                ('price', models.IntegerField(verbose_name='Tovar narxi')),
                ('about', models.TextField(verbose_name='Tovar haqida')),
                ('star', models.IntegerField(verbose_name='Tovar yulduzchalari')),
                ('discut', models.IntegerField(blank=True, verbose_name='Tovar chegirmasi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
